clear
% fmrxCust(10, 92.9)
% 18500 watts (92.9 FM)
fc = 88.5e6; % Center frequency (Hz)
fs  = .3e6; % (hz) % success at 2.6 and tunergain at 100 (max 3.2e6)
      % can not be 3e5< fs <=9e5 
n = 50e3; % samples/frame  [maximum is 375e3]
N = 100; % number of CPIs
% n*N/sampleRate
% 3e8/fc/4*39.4% bunny ears should be a little less than this size (inches)
g = 45;
sdrRx{1} = comm.SDRRTLReceiver(...
  'CenterFrequency', fc, ...
  'EnableTunerAGC',  false, ... % set to false to manually tune
  'SampleRate',      fs, ...
  'SamplesPerFrame', n, ...%   'TunerGain',100, ...
   'TunerGain',g, ...
  'OutputDataType',  'single');
g = 20;

sdrRx{2} = comm.SDRRTLReceiver(...
  'CenterFrequency', fc, ...
  'EnableTunerAGC',  false, ...% set to false to manually tune
  'SampleRate',      fs, ...
  'SamplesPerFrame', n, ...%   'TunerGain',100, ...
  'TunerGain',g, ...
  'RadioAddress','01',...
  'OutputDataType',  'single');

DATA = mainFreqAnal(sdrRx,N);


